input.onButtonPressed(Button.A, function () {
    led.plot(4, 4)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(4, 3)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(4, 2)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(3, 2)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(2, 2)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(2, 2)
})
basic.forever(function () {
	
})
